from .instrument import (
    emit_decision,
    build_decision_fallback,
    instrument_decision,
    decide_then_act,
    ALLOWED_DECISION_TYPES,
    instrument_node,
    new_trace_context,
    validate_decision_payload,
    TRACE_ID_KEY,
    TENANT_ID_KEY,
    VECTOR_CLOCK_KEY,
    PARENT_SPAN_KEY,
)
from .core import (
    SpanContext,
    begin_span,
    build_span,
    emit_decision_event,
    normalize_node_result,
    normalize_llm_response,
    validate_and_parse_llm_json,
    validate_rationale,
    ParseFailureReason,
    register_coverage_point,
    mark_covered,
    get_coverage_report,
    add_redact_key,
    DECISION_COVERAGE_POINTS,
    RATIONALE_PROMPT_TEMPLATE,
)
from .taxonomy import SemanticFailureType, classify_error
from .client import emit_span

__all__ = [
    "instrument_node",
    "instrument_decision",
    "decide_then_act",
    "emit_decision",
    "validate_decision_payload",
    "build_decision_fallback",
    "ALLOWED_DECISION_TYPES",
    "new_trace_context",
    "TRACE_ID_KEY",
    "TENANT_ID_KEY",
    "VECTOR_CLOCK_KEY",
    "PARENT_SPAN_KEY",
    "SpanContext",
    "begin_span",
    "build_span",
    "emit_decision_event",
    "normalize_node_result",
    "normalize_llm_response",
    "validate_and_parse_llm_json",
    "validate_rationale",
    "ParseFailureReason",
    "register_coverage_point",
    "mark_covered",
    "get_coverage_report",
    "add_redact_key",
    "DECISION_COVERAGE_POINTS",
    "RATIONALE_PROMPT_TEMPLATE",
    "SemanticFailureType",
    "classify_error",
    "emit_span",
]
